name: Changelog

on:
  push:
    tags:
      - v*
      - "!v0.0.0"

permissions:
  contents: read

jobs:
  generate_changelog:
    name: Generate changelog
    if: github.repository == 'argoproj/argo-workflows'
    permissions:
      contents: write  # for peter-evans/create-pull-request to create branch
      pull-requests: write  # for peter-evans/create-pull-request to create a PR
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: main
          fetch-depth: 0
      - run: git fetch --prune --prune-tags
      - run: git tag -l 'v*'
      # avoid invoking `make` to reduce the risk of a Makefile bug failing this workflow
      - run: ./hack/changelog.sh > CHANGELOG.md
      - uses: peter-evans/create-pull-request@67ccf781d68cd99b580ae25a5c18a1cc84ffff1f # v7.0.6
        with:
          title: 'docs: update CHANGELOG.md for ${{ github.ref_name }}'
          commit-message: 'docs: update CHANGELOG.md for ${{ github.ref_name }}'
          branch: create-pull-request/changelog
          signoff: true
